"""empty message

Revision ID: 02218e77340f
Revises: b0d4f011d543
Create Date: 2024-05-08 20:19:17.807531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02218e77340f'
down_revision = 'b0d4f011d543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Address', sa.String(length=300), nullable=True))
        batch_op.alter_column('Dep',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.drop_column('Id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Id', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('Dep',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('Address')

    op.create_table('address',
    sa.Column('UID', sa.INTEGER(), nullable=False),
    sa.Column('VID', sa.INTEGER(), nullable=False),
    sa.Column('Adr', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['UID'], ['user.UID'], ),
    sa.ForeignKeyConstraint(['VID'], ['vote.VID'], )
    )
    # ### end Alembic commands ###
