"""empty message

Revision ID: 28f7ee3bc77f
Revises: 02218e77340f
Create Date: 2024-05-08 20:58:09.569389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f7ee3bc77f'
down_revision = '02218e77340f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('Sold',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('Sold',
               existing_type=sa.String(length=300),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    # ### end Alembic commands ###
