"""empty message

Revision ID: 39c06d7a5af6
Revises: 
Create Date: 2024-05-07 07:22:33.513033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c06d7a5af6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote_type',
    sa.Column('TID', sa.Integer(), nullable=False),
    sa.Column('Utype', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('TID')
    )
    op.create_table('cand_prom',
    sa.Column('CID', sa.Integer(), nullable=False),
    sa.Column('PID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CID'], ['candidate.CID'], ),
    sa.ForeignKeyConstraint(['PID'], ['promise.PID'], ),
    sa.PrimaryKeyConstraint('CID', 'PID')
    )
    op.drop_table('candprom')
    op.drop_table('votetype')
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.alter_column('UID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('VID',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('CID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('promise', schema=None) as batch_op:
        batch_op.alter_column('PID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('RID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('UID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('VID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('VID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('UID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('RID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('promise', schema=None) as batch_op:
        batch_op.alter_column('PID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('CID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.alter_column('VID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('UID',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('votetype',
    sa.Column('TID', sa.INTEGER(), nullable=True),
    sa.Column('Utype', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('TID')
    )
    op.create_table('candprom',
    sa.Column('CID', sa.INTEGER(), nullable=True),
    sa.Column('PID', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['CID'], ['candidate.CID'], ),
    sa.ForeignKeyConstraint(['PID'], ['promise.PID'], )
    )
    op.drop_table('cand_prom')
    op.drop_table('vote_type')
    # ### end Alembic commands ###
