"""empty message

Revision ID: b0d4f011d543
Revises: a9575e62b7b7
Create Date: 2024-05-07 11:05:08.661283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d4f011d543'
down_revision = 'a9575e62b7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote_type',
    sa.Column('TID', sa.Integer(), nullable=False),
    sa.Column('Vtype', sa.Integer(), nullable=True),
    sa.Column('Utype', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('TID')
    )
    op.drop_table('VoteType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VoteType',
    sa.Column('TID', sa.INTEGER(), nullable=True),
    sa.Column('Vtype', sa.INTEGER(), nullable=True),
    sa.Column('Utype', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('TID')
    )
    op.drop_table('vote_type')
    # ### end Alembic commands ###
